name: base
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.4
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.2
  - pip=25.2
  - python=3.10.16
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - pip:
      - absl-py==1.4.0
      - alphafold-colabfold==2.3.6
      - appdirs==1.4.4
      - astunparse==1.6.3
      - attrs==25.3.0
      - biopython==1.82
      - cachetools==5.5.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - chex==0.1.86
      - contourpy==1.3.2
      - cycler==0.12.1
      - dm-haiku==0.0.13
      - dm-tree==0.1.9
      - flatbuffers==25.2.10
      - fonttools==4.59.1
      - gast==0.4.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.14.0
      - idna==3.10
      - immutabledict==4.2.1
      - importlib-metadata==4.13.0
      - jmp==0.0.4
      - keras==2.15.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - ml-collections==1.1.0
      - ml-dtypes==0.2.0
      - namex==0.1.0
      - numpy==1.26.4
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==25.0
      - pandas==1.5.3
      - pillow==11.3.0
      - protobuf==4.25.8
      - py3dmol==2.5.2
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.1.0
      - rsa==4.9.1
      - scipy==1.15.3
      - six==1.17.0
      - tabulate==0.9.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-cpu==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - toolz==1.0.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.14.2
      - zipp==3.23.0
